// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPWa8WauBp38qHcxnQ0jZMjtiYYC275As',
    appId: '1:999646883076:web:7d62bf21a3da9cf051f451',
    messagingSenderId: '999646883076',
    projectId: 'kids-rijal',
    authDomain: 'kids-rijal.firebaseapp.com',
    storageBucket: 'kids-rijal.appspot.com',
    measurementId: 'G-QD9BCY4V3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSjV4Ngo8cG12OU2RRlhyilaQOH1A-FjI',
    appId: '1:999646883076:android:db64e48edbd87f5651f451',
    messagingSenderId: '999646883076',
    projectId: 'kids-rijal',
    storageBucket: 'kids-rijal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEAdrG0c7MSaewYXQusGakM5hW8jHDifs',
    appId: '1:999646883076:ios:bb420e82a8250d5851f451',
    messagingSenderId: '999646883076',
    projectId: 'kids-rijal',
    storageBucket: 'kids-rijal.appspot.com',
    iosClientId: '999646883076-sof7dknghn180a3otn482gm1adclt9qv.apps.googleusercontent.com',
    iosBundleId: 'com.arrijal.kidsRijal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEAdrG0c7MSaewYXQusGakM5hW8jHDifs',
    appId: '1:999646883076:ios:bb420e82a8250d5851f451',
    messagingSenderId: '999646883076',
    projectId: 'kids-rijal',
    storageBucket: 'kids-rijal.appspot.com',
    iosClientId: '999646883076-sof7dknghn180a3otn482gm1adclt9qv.apps.googleusercontent.com',
    iosBundleId: 'com.arrijal.kidsRijal',
  );
}
